### ISSUE TITLE
Unclear how to run files

### ISSUE THREAD

**Issue by pajcek11** [untoxa/GBTD_GBMB#2]
Hello!

I am having trouble figuring out how to run this program. The original program had an .exe and one would just run it. Here, there are a lot more files, and my Win10 recognized only a couple of types. I tried to open the HLP file, but it did nothing.

Could you please be so kind and compile a binary for Windows or Linux?
Or could you kindly write a short instruction on how to run these files and what the dependencies are?

Thank you very much!
Sorry for posting such an issue.

**Comment by untoxa** [comment]
https://github.com/gbdk-2020/GBTD_GBMB/releases/tag/2.4.4
