### ISSUE TITLE
macos version

### ISSUE THREAD

**Issue by ghost** [untoxa/GBTD_GBMB#4]
Hi

Can you make it for macos using Lazarus?

https://www.lazarus-ide.org/

**Comment by ghost** [comment]
It don't work on mac.
Can somebody help?

**Comment by untoxa** [comment]
Unfortunately, that is not easily doable. We are not planning to make the mac port of these tools because they are obsolete. Suggested workflow is to use something like aseprite or tileed, export to png images and then use the png2asset tool.
