### ISSUE TITLE
Optional const

### ISSUE THREAD

**Issue by 1Dr490n** [untoxa/GBTD_GBMB#5]
The arrays in the exported C-files should be constant by default, but there should be an option to make them non-constant.

**Comment by untoxa** [comment]
what for? initializers for the non-constant arrays occupy precious bank 0 and the equal size in WRAM. if you really want that for the one file, better remove that const qualifier by hand, to make sure that you are doing that knowingly.

**Comment by 1Dr490n** [comment]
I need to edit the exported map at runtime

**Comment by untoxa** [comment]
memcpy() is your friend

**Comment by 1Dr490n** [comment]
You mean I should create a second array and copy the first array into the second? Why not directly a non-constant array?

**Comment by untoxa** [comment]
because, as i said earlier, the initializer for that non-constant array of the equal size occupy the precious space in bank0. and can not be moved into any other bank. you overflow bank0 very quickly.
